In [ ]:
import os
from tqdm import tqdm
from edgar import Company
from edgar import set_identity
import pandas as pd

import src.config as config

name = os.getenv("NAME", "Your Name")
email = os.getenv("EMAIL", "Your Email")

set_identity(f"{name} {email}")


sp500 = pd.read_csv(os.path.join(config.general['paths']['input'], 's&p500.csv'), sep=';', dtype={'CIK': str})
pbar = tqdm(zip(sp500.CIK, sp500.Symbol), total=len(sp500), desc="Processing CIKs")
symbols, filings = [], []
for cik, symbol in pbar:
    element = symbol if pd.isna(cik) else cik
    pbar.set_description(f"Processing CIK: {element}")
    company = Company(element)
    symbols.append(element)
    filings.append(len(company.get_filings()))

df = pd.DataFrame({"Symbol": symbols, "Filings": filings}).sort_values(by="Filings", ascending=True)

In [59]:
df

      Symbol  Filings
385  2058873      131
358  2041610      203
404  2023554      205
214  1996810      207
416  1964738      255
..       ...      ...
58     70858    50425
225   886982    90341
110   831001    90657
323   895421   106600
269    19617   163590

[503 rows x 2 columns]

In [ ]:
from edgar import set_identity
from edgar import Company

company = Company("AAPL")
filings = company.get_filings(form="10-K")

In [39]:
filings[0].xbrl().statements.income_statement().to_dataframe(view="summary")

,concept,label,standard_concept,2025-09-27 (FY),2024-09-28 (FY),2023-09-30 (FY),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_RevenueFromContractWithCustomerExcludi...,Net sales,Revenue,4.161610e+11,3.910350e+11,3.832850e+11,4,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
1,us-gaap_CostOfGoodsAndServicesSold,Cost of sales,CostOfGoodsAndServicesSold,2.209600e+11,2.103520e+11,2.141370e+11,4,False,False,False,None,None,None,None,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
2,us-gaap_GrossProfit,Gross margin,GrossProfit,1.952010e+11,1.806830e+11,1.691480e+11,3,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_OperatingIncomeLoss,us-gaap_StatementLineItems
3,us-gaap_OperatingExpensesAbstract,Operating expenses:,NaN,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
4,us-gaap_ResearchAndDevelopmentExpense,Research and development,ResearchAndDevelopmentExpenses,3.455000e+10,3.137000e+10,2.991500e+10,5,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
5,us-gaap_SellingGeneralAndAdministrativeExpense,"Selling, general and administrative",SellingGeneralAndAdminExpenses,2.760100e+10,2.609700e+10,2.493200e+10,5,False,False,False,None,None,None,None,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
6,us-gaap_OperatingExpenses,Total operating expenses,TotalOperatingExpenses,6.215100e+10,5.746700e+10,5.484700e+10,5,False,False,False,None,None,None,None,NaN,-1.0,1.0,us-gaap_OperatingIncomeLoss,us-gaap_OperatingExpensesAbstract
7,us-gaap_OperatingIncomeLoss,Operating income,OperatingIncomeLoss,1.330500e+11,1.232160e+11,1.143010e+11,4,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
8,us-gaap_NonoperatingIncomeExpense,"Other income/(expense), net",NonoperatingIncomeExpense,-3.210000e+08,2.690000e+08,-5.650000e+08,4,False,False,False,None,None,None,None,NaN,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
9,us-gaap_IncomeLossFromContinuingOperationsBefo...,Income before provision for income taxes,PretaxIncomeLoss,1.327290e+11,1.234850e+11,1.137360e+11,3,False,False,False,None,None,None,None,credit,1.0,1.0,us-gaap_NetIncomeLoss,us-gaap_StatementLineItems
10,us-gaap_IncomeTaxExpenseBenefit,Provision for income taxes,IncomeTaxes,2.071900e+10,2.974900e+10,1.674100e+10,3,False,False,False,None,None,None,None,debit,-1.0,1.0,us-gaap_NetIncomeLoss,us-gaap_StatementLineItems
11,us-gaap_NetIncomeLoss,Net income,NetIncome,1.120100e+11,9.373600e+10,9.699500e+10,3,False,False,False,None,None,None,None,credit,1.0,1.0,NaN,us-gaap_StatementLineItems
12,us-gaap_EarningsPerShareAbstract,Earnings per share:,NaN,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
13,us-gaap_EarningsPerShareBasic,Basic (in dollars per share),NaN,7.490000e+00,6.110000e+00,6.160000e+00,4,False,False,False,None,None,None,None,NaN,NaN,1.0,NaN,us-gaap_EarningsPerShareAbstract
14,us-gaap_EarningsPerShareDiluted,Diluted (in dollars per share),NaN,7.460000e+00,6.080000e+00,6.130000e+00,4,False,False,False,None,None,None,None,NaN,NaN,1.0,NaN,us-gaap_EarningsPerShareAbstract
15,us-gaap_WeightedAverageNumberOfSharesOutstandi...,Shares used in computing earnings per share:,NaN,NaN,NaN,NaN,3,True,False,False,None,None,None,None,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
16,us-gaap_WeightedAverageNumberOfSharesOutstandi...,Basic (in shares),SharesAverage,1.494850e+10,1.534378e+10,1.574423e+10,4,False,False,False,None,None,None,None,NaN,1.0,1.0,us-gaap_WeightedAverageNumberOfDilutedSharesOu...,us-gaap_WeightedAverageNumberOfSharesOutstandi...
17,us-gaap_WeightedAverageNumberOfDilutedSharesOu...,Diluted (in shares),SharesFullyDilutedAverage,1.500470e+10,1.540810e+10,1.581255e+10,4,False,False,False,None,None,None,None,NaN,1.0,1.0,NaN,us-gaap_WeightedAverageNumberOfSharesOutstandi...

In [ ]:
from edgar import set_identity
from edgar import Company

name = os.getenv("NAME", "Your Name")
email = os.getenv("EMAIL", "Your Email")

set_identity(f"{name} {email}")

company = Company(element)
filings = company.get_filings()
filing_year = next(f for f in filings if f.filing_date.year==2018)